baseURL = "https://localhost:1313/"
baseURLProduction = "https://m-syc.github.io/sgp-nt/"

title = "SGP-NT"
languageCode = "en"
theme = "blowfish"
enableRobotsTXT = true
defaultContentLanguage = "en"
relativeURLs = true
canonifyURLs = true

[params]
defaultTheme = "light"
showBackToTop = true
enableSearch = true
homepage.showRecent = false
disableImageOptimization = true

[Environment]
  [Environment.production]
  baseURL = "https://m-syc.github.io/sgp-nt/"

  [Environment.development]
  baseURL = "https://localhost:1313/"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true  # pozwala na <img>, <iframe> itp.

[caches]
  [caches.images]
    dir = ':cacheDir/images'


[[menu.main]]
name = "Converter"
url = "/converter"
weight = 4
