baseURL = "https://localhost:1313/"

title = "SGP-NT"
languageCode = "en"
theme = "blowfish"
enableRobotsTXT = true
defaultContentLanguage = "en"
relativeURLs = true
canonifyURLs = true

[params]
defaultTheme = "light"
showBackToTop = true
enableSearch = true
homepage.showRecent = false
disableImageOptimization = true

baseURLProduction = "https://m-syc.github.io/sgp-nt/"

[Environment]
  [Environment.production]
  baseURL = "https://m-syc.github.io/sgp-nt/"

  [Environment.development]
  baseURL = "https://localhost:1313/"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true  # pozwala na <img>, <iframe> itp.

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
name = "Training 1"
url = "/training1/"
weight = 1

[[menu.main]]
name = "Race 1"
url = "/race1/"
weight = 2

[[menu.main]]
name = "Race 2"
url = "/race2"
weight = 3
