baseURL = "https://twoja_nazwa_uzytkownika.github.io/"
title = "Wydarzenie – 8 Dni"
theme = "blowfish"
languageCode = "pl"
enableRobotsTXT = true

[params]
defaultTheme = "light"
showBackToTop = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[[menu.main]]
name = "Dzień 1"
url = "/training1/"
weight = 1

[[menu.main]]
name = "Dzień 2"
url = "/training2/"
weight = 2
